# Generated by Django 2.2.8 on 2021-01-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportId', models.CharField(max_length=20, verbose_name='报告ID')),
                ('generationTime', models.DateTimeField(verbose_name='报告生成时间')),
                ('suspectId', models.CharField(max_length=20, verbose_name='被举报者假名')),
                ('reporterId', models.CharField(max_length=20, verbose_name='举报人假名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('errorType', models.CharField(choices=[('0', 'SELF'), ('1', 'CERT'), ('2', 'SEMANTIC')], default='0', max_length=1, verbose_name='异常类型')),
                ('errorCode', models.CharField(max_length=2, verbose_name='异常代码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'mbrs',
            },
        ),
    ]
