# Generated by Django 2.2.8 on 2021-01-21 09:44

import apps.mbrs.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mbrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbr',
            name='errorType',
            field=enumfields.fields.EnumIntegerField(enum=apps.mbrs.models.ErrorType, verbose_name='异常类型'),
        ),
    ]
